apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kube.service_account_name }}
  namespace: {{ .Values.common.namespace }} # SA 所属命名空间
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mss-sa-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mss-sa-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kube.service_account_name }}
    namespace: {{ .Values.common.namespace }}
roleRef:
  kind: ClusterRole
  name: mss-sa-role
  apiGroup: rbac.authorization.k8s.io