{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mooncake.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mooncake.labels" . | nindent 4 }}
{{- end -}}
